# Docker Compose override for development
services:
  # Development overrides for hot reloading
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true

  api:
    volumes:
      - ./backend:/app
    environment:
      - RELOAD=true
      - DEBUG=true

  fastmcp:
    volumes:
      - ./fastmcp:/app

  # Expose additional ports for development
  postgres:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6380:6379"